add_lunch_combo pme-userdebug
add_lunch_combo pme-user
add_lunch_combo pme-eng
add_lunch_combo axon7-userdebug
add_lunch_combo axon7-user
add_lunch_combo axon7-eng
add_lunch_combo oneplus3-userdebug
add_lunch_combo oneplus3-user
add_lunch_combo oneplus3-eng
