add_lunch_combo pme-userdebug
add_lunch_combo pme-user
add_lunch_combo pme-eng
add_lunch_combo axon7-userdebug
add_lunch_combo axon7-user
add_lunch_combo axon7-eng
add_lunch_combo oneplus3-userdebug
add_lunch_combo oneplus3-user
add_lunch_combo oneplus3-eng
add_lunch_combo cheeseburger-userdebug
add_lunch_combo cheeseburger-user
add_lunch_combo cheeseburger-eng
add_lunch_combo gemini-userdebug
add_lunch_combo gemini-user
add_lunch_combo gemini-eng
add_lunch_combo land-userdebug
add_lunch_combo land-user
add_lunch_combo land-eng
add_lunch_combo z2_plus-userdebug
add_lunch_combo z2_plus-user
add_lunch_combo z2_plus-eng
